// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX_NlJIpGvXH_ndyOG_eqWh3VTXawUaV4',
    appId: '1:661733301222:web:c9496e026e340b02f59427',
    messagingSenderId: '661733301222',
    projectId: 'healthcareapp-6e9f0',
    authDomain: 'healthcareapp-6e9f0.firebaseapp.com',
    storageBucket: 'healthcareapp-6e9f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYFty_vcI_oEAw8Z7NwO8jqDfUI8eAmws',
    appId: '1:661733301222:android:8a4d3621cdb5dad1f59427',
    messagingSenderId: '661733301222',
    projectId: 'healthcareapp-6e9f0',
    storageBucket: 'healthcareapp-6e9f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBY9vBZjkphX7hTt0qVTYbLdOEkGNrG_8',
    appId: '1:661733301222:ios:542a8988fda85a52f59427',
    messagingSenderId: '661733301222',
    projectId: 'healthcareapp-6e9f0',
    storageBucket: 'healthcareapp-6e9f0.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX_NlJIpGvXH_ndyOG_eqWh3VTXawUaV4',
    appId: '1:661733301222:web:d0f9f0886bcd2241f59427',
    messagingSenderId: '661733301222',
    projectId: 'healthcareapp-6e9f0',
    authDomain: 'healthcareapp-6e9f0.firebaseapp.com',
    storageBucket: 'healthcareapp-6e9f0.firebasestorage.app',
  );
}
